### ISSUE TITLE
 favourite OTAs/Factory images？

### ISSUE THREAD

**Issue by youyim** [alephsecurity/abootool#9]
hi， favourite OTAs/Factory images？I use nubia (zte) Z18,it is sdm845.
![2018-10-12 15-20-49](https://user-images.githubusercontent.com/19865880/46854086-69972580-ce32-11e8-9e7c-a3decf64983e.png)

![2018-10-12 15-18-41](https://user-images.githubusercontent.com/19865880/46853982-318fe280-ce32-11e8-9789-35909c8c0913.png)

**Comment by P3nguin-M** [comment]
try not unpacking the zip file and calling the .zip, such as:
$ ./abootool.py -a "/path/to/file/ota.zip"

**Comment by youyim** [comment]
> try not unpacking the zip file and calling the .zip, such as:
> $ ./abootool.py -a "/path/to/file/ota.zip"

![2019-01-14 20-47-49](https://user-images.githubusercontent.com/19865880/51113655-b3324a80-183d-11e9-8a10-fba89f19883d.png)
The same result

**Comment by P3nguin-M** [comment]
While I was working on a OnePlus firmware, I used the file: **OnePlus3Hydrogen_16_OTA_014_all_1702242121_0c67dd86616c455d.zip  **
When I added the firmware to the application, my command was exactly:
./abootool.py -a "OnePlus3Hydrogen_16_OTA_014_all_1702242121_0c67dd86616c455d.zip"

Haven't looked deep into the code yet, plus I'm new to python and maybe have a month experience in it... What I can tell you is that with quotes it worked flawlessly for me, before I add them, I have the same issue. Try quotes?!
